import { z } from "zod";

import geometryVersionsData from "@/features/atlas/presets/data/geometry-versions.json";
import { publicAssetUrl } from "@/lib/public-asset-url";

/** Generated by the geographic pipeline: the SHA-256 of each committed topology artifact. */
const geometryVersionsSchema = z.record(
	z.string(),
	z.string().regex(/^[0-9a-f]{64}$/),
);

const geometryVersions = geometryVersionsSchema.parse(geometryVersionsData);

/**
 * Request geometry by content rather than by name.
 *
 * A topology is a large, long-lived public asset, so a browser or CDN will happily keep serving
 * the copy it already has. Binding the request to the generated digest means a new application
 * bundle can never pair its manifest with a topology from a different build.
 */
export function geometryUrl(presetId: string): string {
	const version = geometryVersions[presetId];
	if (!version)
		throw new Error(
			`No generated geometry version for the ${presetId} preset. Regenerate the map assets with pnpm geo:build.`,
		);
	return `${publicAssetUrl(`maps/${presetId}.topo.json`)}?v=${version.slice(0, 12)}`;
}
